services:
  app:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching on Windows
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WEBPACK_DEV_SERVER_HOST=0.0.0.0
      - REACT_APP_API_URL=http://localhost:3001
    ports:
      - "3000:3000"    # React
      - "3001:3001"    # Express API
      - "9229:9229"  # Debug port
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./server:/app/server
      - ./cfg:/app/cfg
    command: >
      sh -c "
        npm run server & 
        npm start
      "